// web-client/src/Content/SubMenu/SubMenu.tsx
import './SubMenu.scss'
import { Button, Nav} from 'react-bootstrap';
import { useState } from 'react';
import ModalTransaction from '../ModalTransaction/ModalTransaction';


export default function SubMenu() {
  const [isShow, setIsShow] = useState(false)

  function Modal(){
    return(
      isShow==true?
      <ModalTransaction transaction={null} title="Изменить" refIsHide={setIsShow}/>
      :null
    )
  }

  return (
    <Nav className="justify-content-end submenu" activeKey="/home">
          <Nav.Item>
          <Button variant="outline-primary" onClick={()=>setIsShow(true)}>
          Добавить
          </Button>         
          {Modal()}
          </Nav.Item>
    </Nav>
  );
}

// ClientApp/WebClient/src/app/submenu/submenu.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-submenu',
  templateUrl: './submenu.component.html',
  styleUrls: ['./submenu.component.sass']
})
export class SubmenuComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<ul class="nav justify-content-end">
    <li class="nav-item topMenu">
        <button type="button" class="btn btn-outline-primary">Добавить</button>
    </li>
  </ul>
