// ClientApp/web-client/src/SubMenu/SubMenu.tsx
import React from 'react';
import './SubMenu.scss'
import { Nav, Button} from 'react-bootstrap';

function SubMenu() {
  return (
    <Nav className="justify-content-end submenu" activeKey="/home">
          <Nav.Item>
          <Button variant="outline-primary">Добавить</Button>
          </Nav.Item>
    </Nav>
  );
}

export default SubMenu;

// ClientApp/WebClient/src/app/submenu/submenu.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-submenu',
  templateUrl: './submenu.component.html',
  styleUrls: ['./submenu.component.sass']
})
export class SubmenuComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<ul class="nav justify-content-end">
    <li class="nav-item topMenu">
        <button type="button" class="btn btn-outline-primary">Добавить</button>
    </li>
  </ul>
